meta_product_name: "Younguage"
meta_title: "Younguage - Learn a language"
meta_description: "We open you to the world thanks to a true language immersion from your home."
meta_image: "younguage1.png" # should exist in `app/assets/images/`
twitter_account: "@younguage"
